# Generated by Django 4.2.4 on 2023-10-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_a_profile_email_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'حساب کاربری', 'verbose_name_plural': 'حساب\u200cهای کاربری'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='a', max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fathers_name',
            field=models.CharField(max_length=25, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='a', max_length=30, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/images', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='a', max_length=150, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='melicode',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='a', max_length=150, verbose_name='نام کاربری'),
        ),
    ]
