# Generated by Django 4.2.4 on 2023-09-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_slug_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('created',)},
        ),
    ]
