# Generated by Django 4.2.4 on 2023-09-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
