# Generated by Django 4.2.4 on 2023-10-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_crreated_at_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='title',
            field=models.CharField(max_length=35),
        ),
    ]
