# Generated by Django 4.2.4 on 2023-10-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_like_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='slug',
        ),
    ]
